### ISSUE TITLE
get-file should report if a file is not present

### ISSUE THREAD

**Issue by tgpfeiffer** [retz/retz#80]
At the moment, when the `get-file` command is invoked with a non-existing file name, the response will simply be empty, but there will be no indication of a failure:

```
$ ./bin/retz-client -C retz.properties get-file -id 1 --path resultszxxx
Using jar file 'retz-client/build/libs/retz-client-0.0.30-all.jar'
[main] INFO io.github.retz.cli.Launcher - retz-client-0.0.30 (0.0.28-33-g521ac64)
[main] INFO io.github.retz.cli.FileConfiguration - Authentication enabled
[main] INFO io.github.retz.cli.ClientCLIConfig - Client only config: retz.server.uri=http://mesos3:9090
[main] INFO io.github.retz.cli.Launcher - Command: get-file, Config file: retz.properties
[main] INFO io.github.retz.auth.Authenticator - javax.crypto.Mac instance with HmacSHA256 initialized in 48 ms.
[main] INFO io.github.retz.cli.CommandGetFile - Getting file resultszxxx (offset=0, length=-1) of a job(id=1)
[main] INFO io.github.retz.cli.CommandGetFile - ============== printing resultszxxx of job id=1 ================
$ 
```

I think both this command and also the `ClientHelper.getWholeFile()` method should report an error if the file does not exist.

**Comment by kuenishi** [comment]
As https://github.com/retz/retz/commit/1968423be744f21e1bb7d5ada5272a19db9a4934 and https://github.com/retz/retz/commit/98272aa0f4fe9b6bdfd61d503fa94cf49b520619 are now pushed, this should be fixed in upcoming 0.0.33 or later.

**Comment by kuenishi** [comment]
TODO: add inttest to file existence reporting, or non-existent job reporting.

**Comment by kuenishi** [comment]
Tests added: e70077dd7e

**Comment by tgpfeiffer** [comment]
In 0.1.1 this is still broken for me. Providing an invalid job ID is reported correctly ("Cannot get file: io.github.retz.protocol.exception.JobNotFoundException: No such job: id=3"), but `get-file` still does not report properly if a file does not exist.

File exists (but is empty):
```
[main] INFO io.github.retz.cli.CommandGetFile - Getting file results/x (offset=0, length=-1) of a job(id=2)
[main] INFO io.github.retz.cli.CommandGetFile - ============== printing results/x of job id=2 ================
[main] INFO io.github.retz.cli.CommandGetFile - offset=0
```

File does not exist:
```
[main] INFO io.github.retz.cli.CommandGetFile - Getting file results/abc (offset=0, length=-1) of a job(id=2)
[main] INFO io.github.retz.cli.CommandGetFile - ============== printing results/abc of job id=2 ================
[main] INFO io.github.retz.cli.CommandGetFile - Job: appid=foo, id=2, scheduled=2016-12-08T12:59:40.618+09:00, cmd='mkdir results && touch results/x && hostname'
[main] INFO io.github.retz.cli.CommandGetFile - 	started=2016-12-08T12:59:40.828+09:00, finished=2016-12-08T12:59:40.912+09:00, state=FINISHED, result=0
```

**Comment by kuenishi** [comment]
662714a0dd3247e4ffe8d8b should be a fix for this.

```
INFO ============== printing no of job id=1 ================
ERROR java.io.FileNotFoundException: no
java.io.FileNotFoundException: no
        at io.github.retz.web.ClientHelper.getWholeFile(ClientHelper.java:137)
        at io.github.retz.web.ClientHelper.getWholeFile(ClientHelper.java:72)
        at io.github.retz.cli.CommandGetFile.handle(CommandGetFile.java:86)
        at io.github.retz.cli.Launcher.execute(Launcher.java:73)
        at io.github.retz.cli.Launcher.main(Launcher.java:54)
```

CLI has been throwing FileNotFoundException and closing System.out in case of file not being found this since while ago, but https://github.com/retz/retz/commit/6c4139d9256d3eba1856900df9238ef92b24be87 brought this up by printing all logs to standard output.

**Comment by tgpfeiffer** [comment]
Yes, confirmed as fixed.
